ports:
- port: 8050
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
tasks:
- init: /workspace/dash-and-jupyterlab-with-gitpod/run.sh
  command: cp -r /workspace/dash-and-jupyterlab-with-gitpod/.jupyter /home/gitpod/
